#!/bin/bash


if [ -z $1 ]; then
  echo "You must enter a parameter:"
  echo "\"on\"  - turn the backlight on"
  echo "\"off\" - turn the backlight off"
  exit -1
fi

command=$1

case $command in
   "off"|"OFF")
      echo "Found off parameter"
      # turn backlight off
      if [ -x "/sys/class/backlight/rpi_backlight/bl_power" ]; then
         sudo tee -a /sys/class/backlight/rpi_backlight/bl_power << EOF
1
EOF
      fi
      if [ -f "/sys/class/backlight/10-0045/brightness" ]; then
         echo "echo 0 > /sys/class/backlight/10-0045/brightness"
         echo 0 > /sys/class/backlight/10-0045/brightness
      fi
;;
   "on"|"ON")
      echo "Found on parameter"
      # turn backlight on
      if [ -x "/sys/class/backlight/rpi_backlight/bl_power" ]; then
         sudo tee -a /sys/class/backlight/rpi_backlight/bl_power << EOF
0
EOF
      fi
      if [ -f "/sys/class/backlight/10-0045/brightness" ]; then
         echo "echo 150 > /sys/class/backlight/10-0045/brightness"
         echo 150 > /sys/class/backlight/10-0045/brightness
      fi
;;
   "dim"|"dim")
      echo "Found dim parameter"
      if [ -f "/sys/class/backlight/10-0045/brightness" ]; then
         echo "echo 30 > /sys/class/backlight/10-0045/brightness"
         echo 30 > /sys/class/backlight/10-0045/brightness
      fi
;;

esac
