#!/bin/bash

MATRIX_IO_DIR=~/source/github.com/matrix-io
MATRIX_IO_REPO=https://github.com/matrix-io

if [ ! -d "$MATRIX_IO_DIR" ]; then
   mkdir -p "$MATRIX_IO_DIR"
fi


clone_pull_repo() {
    cd "$MATRIX_IO_DIR"
    if [ ! -d "$1" ]; then
       git clone $MATRIX_IO_REPO/$1.git
    fi
    cd $1
    git pull
}

clone_pull_repo "face-analytics"
clone_pull_repo "malos-eye"
clone_pull_repo "matrix-app-config-helper"
clone_pull_repo "matrix-cli"
clone_pull_repo "matrix-continuity"
clone_pull_repo "matrix-creator-android-things"
clone_pull_repo "matrix-creator-alexa-voice-demo"
clone_pull_repo "matrix-creator-alexa-voice-services"
clone_pull_repo "matrix-creator-documentation"
clone_pull_repo "matrix-creator-fpga"
clone_pull_repo "matrix-creator-hal"
clone_pull_repo "matrix-creator-init"
clone_pull_repo "matrix-creator-malos"
clone_pull_repo "matrix-creator-mcu"
clone_pull_repo "matrix-creator-nfc-unstable-preview"
clone_pull_repo "matrix-creator-openocd"
clone_pull_repo "matrix-creator-quickstart"
clone_pull_repo "matrix-creator-uv-demo"
clone_pull_repo "matrix-cv"
clone_pull_repo "matrix-documentation"
clone_pull_repo "matrix-eventfilter"
clone_pull_repo "matrix-firebase"
clone_pull_repo "matrix-gesture-cpp-sdk"
clone_pull_repo "matrix-gesture-node-sdk"
clone_pull_repo "matrix-gesture-python-sdk"
clone_pull_repo "matrix-ml"
clone_pull_repo "matrix-node-sdk"
clone_pull_repo "matrix-os"
clone_pull_repo "matrix-sdk"
clone_pull_repo "matrix-sensor-template"
clone_pull_repo "matrix-test-altitude-sensor"
clone_pull_repo "matrix-test-monitor-sensor"
clone_pull_repo "matrix-test-temperature-sensor"
clone_pull_repo "nedb"
clone_pull_repo "node-yaml-localize"
clone_pull_repo "protocol-buffers"
clone_pull_repo "xc3sprog"
clone_pull_repo "pi-wifi"

cd "$MATRIX_IO_DIR"
curl -s https://api.github.com/orgs/matrix-io/repos?per_page=200 | \
    jq -c '. .clone_url | while read i; do
        echo $1
        #cd "$MATRIX_IO_DIR"
        #if [ ! -d "$1" ]; then
        #    git clone $MATRIX_IO_REPO/$1.git
        #fi
        #cd $1
        #git pull
    done

#curl -s https://api.github.com/orgs/matrix-io/repos?per_page=200 | \
#   ruby -rubygems -e 'require "json"; JSON.load(STDIN.read).each { |repo| %x[git clone #{repo["clone_url"]} ]}'



