#!/bin/bash

MATRIX_IO_DIR=~/source/github.com/matrix-io
MATRIX_IO_REPO=https://github.com/matrix-io

cd $MATRIX_IO_DIR
if [ ! -d "matrix-creator-openocd" ]; then
   git clone $MATRIX_IO_REPO/matrix-creator-openocd
fi
cd matrix-creator-openocd

git pull

if [ ! -d build ]; then
  mkdir build
fi

#cd build
#cmake ../
#sudo make install

./bootstrap
./configure
make
sudo make install
