#!/bin/bash

MATRIX_IO_DIR=~/source/github.com/matrix-io
MATRIX_IO_REPO=https://github.com/matrix-io

cd $MATRIX_IO_DIR
if [ ! -d "matrix-documentation" ]; then
   git clone $MATRIX_IO_REPO/matrix-documentation
fi
cd matrix-documentation

git pull
#npm install
