#!/bin/bash

MATRIX_IO_DIR=~/source/github.com/matrix-io
MATRIX_IO_REPO=https://github.com/matrix-io

cd $MATRIX_IO_DIR
if [ ! -d "matrix-creator-init" ]; then
   git clone $MATRIX_IO_REPO/matrix-creator-init
fi
cd matrix-creator-init

git pull
if [ ! -d build ]; then
   mkdir build
fi
cd build
cmake ../
sudo make install
