#!/bin/bash

MATRIX_IO_DIR=~/source/github.com/matrix-io
MATRIX_IO_REPO=https://github.com/matrix-io

cd $MATRIX_IO_DIR
if [ ! -d "matrix-creator-malos" ]; then
   git clone $MATRIX_IO_REPO/matrix-creator-malos
fi
cd matrix-creator-malos

git submodule init && git submodule update

git pull
if [ ! -d build ]; then
   mkdir build
fi
cd build
cmake ../
sudo make install

cd $MATRIX_IO_DIR/matrix-creator-malos/src/js_test
npm install

#node test_driver_info.js
#node test_everloop.js
#node test_humidity.js
#node test_imu.js
#node test_ir_remote.js
#node test_pressure.js
#node test_uv.js
node test_zigbee_bulb.js
node test_zigbee_bulb_color.js
node test_zigbee_bulb_level.js
