#!/bin/bash

MATRIX_IO_DIR=~/source/github.com/matrix-io
MATRIX_IO_REPO=https://github.com/matrix-io

cd $MATRIX_IO_DIR
if [ ! -d "matrix-creator-malos" ]; then
   git clonne $MATRIX_IO_REPO/matrix-creator-malos
fi
cd matrix-creator-malos

git pull
if [ ! -d build ]; then
   mkdir build
fi
cd build
cmake ../
sudo make install
