#!/bin/bash

MATRIX_IO_DIR=~/source/github.com/matrix-io
MATRIX_IO_REPO=https://github.com/matrix-io

cd $MATRIX_IO_DIR
if [ ! -d "matrix-creator-malos-android" ]; then
   git clone $MATRIX_IO_REPO/matrix-creator-malos-android
fi
cd matrix-creator-malos-android

git pull


