#!/bin/bash

MATRIX_IO_DIR=~/source/github.com/matrix-io
MATRIX_IO_REPO=https://github.com/matrix-io

cd $MATRIX_IO_DIR
if [ ! -d "matrix-app-clickgames" ]; then
   git clone $MATRIX_IO_REPO/matrix-app-clickgames
fi
cd matrix-app-clickgames

git pull
#npm install
