#!/bin/bash

MATRIX_IO_DIR=~/source/github.com/matrix-io
MATRIX_IO_REPO=https://github.com/matrix-io

cd $MATRIX_IO_DIR
if [ ! -d "matrix-creator-alexa-voice-services" ]; then
   git clone $MATRIX_IO_REPO/matrix-creator-alexa-voice-services
fi
cd matrix-creator-alexa-voice-services

git pull
#npm install   # this app is Python, not NodeJS
