#!/bin/bash

MATRIX_IO_DIR=~/source/github.com/matrix-io
MATRIX_IO_REPO=https://github.com/matrix-io

cd $MATRIX_IO_DIR
if [ ! -d "matrix-cli" ]; then
   git clonne $MATRIX_IO_REPO/matrix-cli
fi
cd matrix-cli

git pull
npm install
