#!/bin/bash

MATRIX_IO_DIR=~/source/github.com/matrix-io
MATRIX_IO_REPO=https://github.com/matrix-io

cd $MATRIX_IO_DIR
if [ ! -d "MATRIX-TV-Remote" ]; then
   git clone $MATRIX_IO_REPO/MATRIX-TV-Remote
fi
cd MATRIX-TV-Remote

git pull
#npm install
