#!/bin/bash

MATRIX_IO_DIR=~/source/github.com/matrix-io
MATRIX_IO_REPO=https://github.com/matrix-io

cd $MATRIX_IO_DIR
if [ ! -d "matrix-srcjs-apps" ]; then
   git clone $MATRIX_IO_REPO/matrix-srcjs-apps
fi
cd matrix-srcjs-apps

git pull
#npm install
