#!/bin/bash

MATRIX_IO_DIR=~/source/github.com/matrix-io
MATRIX_IO_REPO=https://github.com/matrix-io

cd $MATRIX_IO_DIR
if [ ! -d "matrix-docs-templates" ]; then
   git clone $MATRIX_IO_REPO/matrix-docs-templates
fi
cd matrix-docs-templates

git pull
#npm install
