#!/bin/bash

MATRIX_IO_DIR=~/source/github.com/matrix-io
MATRIX_IO_REPO=https://github.com/matrix-io

cd $MATRIX_IO_DIR
if [ ! -d "protocol-buffers" ]; then
   git clonne $MATRIX_IO_REPO/protocol-buffers
fi
cd protocol-buffers

git pull
if [ ! -d build ]; then
   mkdir build
fi
cd build
cmake ../
make
